keys:
  age: &all
    - &punchly age1g4wr90lug3gmx5fwncmm8t0j4cw35fk8kznhcg0ddga8cp6z7vuqzjkyf9
    - &nano age1umwdghwl6v2dvrluqsydp54uk3tjlxru6m6ju50dgplg6s873frq8p0s4m
    - &tap age15vwrwmrmzexv7nljsarhysazmhsevtuew97tldr3q2l9r2362fns8nusf8
    - &ha-server age1ur6r9rsvt4adj2npsua5cjw4e5t4r6tcfh5y9nudmlqeymaelfpqlrg5gu
creation_rules:
  - path_regex: secrets/hass\.yaml$
    age:
      - *punchly
      - *ha-server
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    age: *all
